kind: pipeline
name: default

steps:
  - name: build
    image: golang:latest
    commands:
      - make build

  - name: notify
    image: plugins/webhook
    urls: https://msgbus.mills.io/ci.mills.io
    when:
      status:
        - success
        - failure
